routes/web.php
<?php

use App\Http\Controllers\Dashboard\ChannelController;
use App\Http\Controllers\Dashboard\CustomerController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\HomestayController;
use App\Http\Controllers\Dashboard\Report\Okupansi\HomestayReportByOkupansiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\AsalCustomerByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\ChannelByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\DaerahHHomestayByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\HomestayByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\JumlahOrangByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\RoomHomestayByTransaksiController;
use App\Http\Controllers\Dashboard\ReservationController;
use App\Http\Controllers\Dashboard\ServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Route::prefix('/d')->group(function () {
    Route::resource('dashboard', DashboardController::class)->only('index');

    Route::resource('customer', CustomerController::class)->only('index');

    Route::resource('services', ServiceController::class)->only('index');

    Route::resource('channels', ChannelController::class)->only('index');

    Route::resource('homestays', HomestayController::class)->only('index');

    Route::resource('reservations', ReservationController::class)->only('index');

    Route::prefix('reports')->name('reports.')->group(function() {

        Route::prefix('transaksi')->name('transaksi.')->group(function() {
            Route::get('export-homestay', [HomestayByTransaksiController::class, 'export'])->name('export-homestay');
            Route::get('export-channel', [ChannelByTransaksiController::class, 'export'])->name('export-channel');
            Route::get('export-jumlah-orang', [JumlahOrangByTransaksiController::class, 'export'])->name('export-jumlah-orang');
            Route::get('export-daerah-homestay', [DaerahHHomestayByTransaksiController::class, 'export'])->name('export-daerah-homestay');
            Route::get('export-asal-customer', [AsalCustomerByTransaksiController::class, 'export'])->name('export-asal-customer');
            Route::get('export-room-homestay', [RoomHomestayByTransaksiController::class, 'export'])->name('export-room-homestay');

            Route::resource('homestays', HomestayByTransaksiController::class)->only('index');
            Route::resource('channel', ChannelByTransaksiController::class)->only('index');
            Route::resource('jumlah-orang', JumlahOrangByTransaksiController::class)->only('index');
            Route::resource('daerah-homestay', DaerahHHomestayByTransaksiController::class)->only('index');
            Route::resource('asal-customer', AsalCustomerByTransaksiController::class)->only('index');
            Route::resource('room-homestay', RoomHomestayByTransaksiController::class)->only('index');
        });

        Route::prefix('okupansi')->name('okupansi.')->group(function() {
            Route::get('export', [HomestayReportByOkupansiController::class, 'export'])->name('export');
            Route::resource('homestays', HomestayReportByOkupansiController::class)->only('index');
        });
    });

});

app/Http/Controllers/Dashboard/Report/Okupansi/HomestayReportByOkupansiController.php
<?php

namespace App\Http\Controllers\Dashboard\Report\Okupansi;

use App\Exports\HomestayByOkupansiExport;
use App\Http\Controllers\Controller;
use App\Models\Reservation;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;

class HomestayReportByOkupansiController extends Controller
{
    public function index(Request $request)
    {
        $defaultPeriod = request()->query('daterange') ?? now()->startOfMonth()->format("m/d/Y") . " - " . now()->endOfMonth()->format("m/d/Y");
        [$startDate, $endDate] = explode(" - ", $defaultPeriod);
        $startDate = Carbon::parse($startDate);
        $endDate = Carbon::parse($endDate);

        $period = $startDate->diffInDays($endDate);

        $reservations = Reservation::selectRaw('homestay_name, sum(long_day) as total_length_of_stay')
            ->join('reservation_details', 'reservations.reservation_id', '=', 'reservation_details.reservation_id')
            ->whereBetween('date_paid_payment', [Carbon::parse($startDate)->startOfDay(), Carbon::parse($endDate)->endOfDay()])
            ->groupBy('homestay_name')->get();

        $chart = Reservation::selectRaw('homestay_name, sum(long_day) as total_length_of_stay')
            ->join('reservation_details', 'reservations.reservation_id', '=', 'reservation_details.reservation_id')
            ->whereBetween('date_paid_payment', [Carbon::parse($startDate)->startOfDay(), Carbon::parse($endDate)->endOfDay()])
            ->groupBy('homestay_name')->get();

        // dd($reservations);
        $labels = array();

        $data['total_length_of_stay'] = array();

        foreach ($chart as $value) {
            if(!in_array($value->homestay_name,$labels))
                $labels[] = $value->homestay_name;
                $night = $value->total_length_of_stay ;
                $persentase = number_format(($night / $period) *100);
                // dd($night, $period, $persentase);

                $data['total_length_of_stay'][] = $persentase;
        }

        return view('pages.reports.okupansi.homestay', compact('reservations', 'defaultPeriod', 'labels', 'data', 'period'));
    }

    public function export()
    {
        $defaultPeriod = request()->query('daterange') ?? now()->startOfMonth()->format("m/d/Y") . " - " . now()->endOfMonth()->format("m/d/Y");

        [$startDate, $endDate] = explode(" - ", $defaultPeriod);
        $startDate = Carbon::parse($startDate)->format("Y-m-d");
        $endDate = Carbon::parse($endDate)->format("Y-m-d");
        // dd($startDate);
        $filename = "homestay-by-okupansi-$startDate-$endDate.xlsx";

        return (new HomestayByOkupansiExport($startDate, $endDate))->download($filename);

    }
}

app/Http/Controllers/Dashboard/Report/Transaksi/AsalCustomerByTransaksiController.php
<?php

namespace App\Http\Controllers\Dashboard\Report\Transaksi;

use App\Exports\AsalCustomerByTransaksiExport;
use App\Http\Controllers\Controller;
use App\Models\Reservation;
use Carbon\Carbon;
use Illuminate\Http\Request;

class AsalCustomerByTransaksiController extends Controller
{
    public function index(Request $request)
    {
        $defaultPeriod = request()->query('daterange') ?? now()->startOfMonth()->format("m/d/Y") . " - " . now()->endOfMonth()->format("m/d/Y");
        [$startDate, $endDate] = explode(" - ", $defaultPeriod);
        $startDate = Carbon::parse($startDate);
        $endDate = Carbon::parse($endDate);

        $reservations = Reservation::selectRaw('provinces.name as province, count(reservations.reservation_id) as amount_reservation,
            sum(long_day) as total_of_length_stay, sum(grand_total) as totals, sum(visitor) as total_lodger')
            ->join('reservation_details', 'reservations.reservation_id', '=', 'reservation_details.reservation_id')
            ->join('customers', 'reservations.customer_id', '=', 'customers.id')
            ->join('provinces', 'customers.province_id', '=', 'provinces.id')
            ->whereBetween('date_paid_payment', [Carbon::parse($startDate)->startOfDay(), Carbon::parse($endDate)->endOfDay()])
            ->groupBy('province')->paginate();

    // dd($reservations);

        $chart = Reservation::selectRaw('provinces.name as province, count(reservations.reservation_id) as amount_reservation,
            sum(long_day) as total_length_of_stay, sum(grand_total) as totals, sum(visitor) as total_lodger')
            ->join('reservation_details', 'reservations.reservation_id', '=', 'reservation_details.reservation_id')
            ->join('customers', 'reservations.customer_id', '=', 'customers.id')
            ->join('provinces', 'customers.province_id', '=', 'provinces.id')
            ->whereBetween('date_paid_payment', [Carbon::parse($startDate)->startOfDay(), Carbon::parse($endDate)->endOfDay()])
            ->groupBy('province')->get();
        // dd($chart);
        $labels = array();

        $data['amount_reservation'] = array();
        $data['total_length_of_stay'] = array();
        $data['totals'] = array();


        foreach ($chart as $value) {
            if(!in_array($value->province,$labels))
                $labels[] = $value->province;

                $data['amount_reservation'][] = $value->amount_reservation;
                $data['total_length_of_stay'][] = $value->total_length_of_stay;
                $data['totals'][] = $value->totals;
        }

        // $channels = Channel::get();

        return view('pages.reports.transaksi.asal-customer', compact('reservations', 'defaultPeriod', 'labels', 'data'));
    }

    public function export()
    {
        $defaultPeriod = request()->query('daterange') ?? now()->startOfMonth()->format("m/d/Y") . " - " . now()->endOfMonth()->format("m/d/Y");

        [$startDate, $endDate] = explode(" - ", $defaultPeriod);
        $startDate = Carbon::parse($startDate)->format("Y-m-d");
        $endDate = Carbon::parse($endDate)->format("Y-m-d");
        // dd($startDate);
        $filename = "asal-customer-by-transaksi-$startDate-$endDate.xlsx";

        return (new AsalCustomerByTransaksiExport($startDate, $endDate))->download($filename);
    }
}

app/Http/Controllers/Dashboard/Report/Transaksi/ChannelByTransaksiController.php
<?php

namespace App\Http\Controllers\Dashboard\Report\Transaksi;

use App\Exports\ChannelByTransaksiExport;
use App\Http\Controllers\Controller;
use App\Models\Reservation;
use Carbon\Carbon;
use Illuminate\Http\Request;

class ChannelByTransaksiController extends Controller
{
    public function index(Request $request)
    {
        $defaultPeriod = request()->query('daterange') ?? now()->startOfMonth()->format("m/d/Y") . " - " . now()->endOfMonth()->format("m/d/Y");
        [$startDate, $endDate] = explode(" - ", $defaultPeriod);
        $startDate = Carbon::parse($startDate);
        $endDate = Carbon::parse($endDate);

        $reservations = Reservation::selectRaw('channel_name, count(reservations.reservation_id) as amount_reservation, count(reservation_details.homestay_name) as amount_homestay,
            sum(grand_total) as totals, sum(long_day) as total_length_of_stay')
            ->join('reservation_details', 'reservations.reservation_id', '=', 'reservation_details.reservation_id')
            ->whereBetween('date_paid_payment', [Carbon::parse($startDate)->startOfDay(), Carbon::parse($endDate)->endOfDay()])
            ->groupBy('channel_name')->paginate();

        // dd($reservations);

        $chart = Reservation::selectRaw('channel_name, count(reservations.reservation_id) as amount_reservation, count(reservation_details.homestay_name) as amount_homestay,
            sum(grand_total) as totals, sum(long_day) as total_length_of_stay')
            ->join('reservation_details', 'reservations.reservation_id', '=', 'reservation_details.reservation_id')
            ->whereBetween('date_paid_payment', [Carbon::parse($startDate)->startOfDay(), Carbon::parse($endDate)->endOfDay()])
            ->groupBy('channel_name')->get();
        // dd($chart);
        $labels = array();

        $data['amount_reservation'] = array();
        $data['total_length_of_stay'] = array();
        $data['totals'] = array();


        foreach ($chart as $value) {
            if(!in_array($value->channel_name,$labels))
                $labels[] = $value->channel_name;

                $data['amount_reservation'][] = $value->amount_reservation;
                $data['total_length_of_stay'][] = $value->total_length_of_stay;
                $data['totals'][] = $value->totals;
        }

        // $channels = Channel::get();

        return view('pages.reports.transaksi.channel-pemesanan', compact('reservations', 'defaultPeriod', 'labels', 'data'));
    }

    public function export()
    {
        $defaultPeriod = request()->query('daterange') ?? now()->startOfMonth()->format("m/d/Y") . " - " . now()->endOfMonth()->format("m/d/Y");

        [$startDate, $endDate] = explode(" - ", $defaultPeriod);
        $startDate = Carbon::parse($startDate)->format("Y-m-d");
        $endDate = Carbon::parse($endDate)->format("Y-m-d");
        // dd($startDate);
        $filename = "channel-by-transaksi-$startDate-$endDate.xlsx";

        return (new ChannelByTransaksiExport($startDate, $endDate))->download($filename);
    }
}

app/Http/Controllers/Dashboard/Report/Transaksi/DaerahHHomestayByTransaksiController.php
<?php

namespace App\Http\Controllers\Dashboard\Report\Transaksi;

use App\Exports\DaerahHomestayByTransaksiExport;
use App\Http\Controllers\Controller;
use App\Models\Reservation;
use Carbon\Carbon;
use Illuminate\Http\Request;

class DaerahHHomestayByTransaksiController extends Controller
{
    public function index(Request $request)
    {
        $defaultPeriod = request()->query('daterange') ?? now()->startOfMonth()->format("m/d/Y") . " - " . now()->endOfMonth()->format("m/d/Y");
        [$startDate, $endDate] = explode(" - ", $defaultPeriod);
        $startDate = Carbon::parse($startDate);
        $endDate = Carbon::parse($endDate);

        $reservations = Reservation::selectRaw('subditrict, count(reservations.reservation_id) as amount_reservation,
            sum(long_day) as total_of_length_stay, sum(grand_total) as totals')
            ->join('reservation_details', 'reservations.reservation_id', '=', 'reservation_details.reservation_id')
            ->join('homestays', 'reservation_details.homestay_id', '=', 'homestays.homestay_id')
            ->whereBetween('date_paid_payment', [Carbon::parse($startDate)->startOfDay(), Carbon::parse($endDate)->endOfDay()])
            ->groupBy('subditrict')->paginate();

    // dd($reservations);

        $chart = Reservation::selectRaw('subditrict, count(reservations.reservation_id) as amount_reservation,
            sum(long_day) as total_length_of_stay, sum(grand_total) as totals')
            ->join('reservation_details', 'reservations.reservation_id', '=', 'reservation_details.reservation_id')
            ->join('homestays', 'reservation_details.homestay_id', '=', 'homestays.homestay_id')
            ->whereBetween('date_paid_payment', [Carbon::parse($startDate)->startOfDay(), Carbon::parse($endDate)->endOfDay()])
            ->groupBy('subditrict')->get();
        // dd($chart);
        $labels = array();

        $data['amount_reservation'] = array();
        $data['total_length_of_stay'] = array();
        $data['totals'] = array();


        foreach ($chart as $value) {
            if(!in_array($value->subditrict,$labels))
                $labels[] = $value->subditrict;

                $data['amount_reservation'][] = $value->amount_reservation;
                $data['total_length_of_stay'][] = $value->total_length_of_stay;
                $data['totals'][] = $value->totals;
        }

        // $channels = Channel::get();

        return view('pages.reports.transaksi.daerah-homestay', compact('reservations', 'defaultPeriod', 'labels', 'data'));
    }

    public function export()
    {
        $defaultPeriod = request()->query('daterange') ?? now()->startOfMonth()->format("m/d/Y") . " - " . now()->endOfMonth()->format("m/d/Y");

        [$startDate, $endDate] = explode(" - ", $defaultPeriod);
        $startDate = Carbon::parse($startDate)->format("Y-m-d");
        $endDate = Carbon::parse($endDate)->format("Y-m-d");
        // dd($startDate);
        $filename = "channel-by-transaksi-$startDate-$endDate.xlsx";

        return (new DaerahHomestayByTransaksiExport($startDate, $endDate))->download($filename);
    }
}

resources/views/pages/reports/okupansi/homestay.blade.php
@extends('layouts.master')
@section('title', 'Homestay Report By Okupansi')

@section('page-css')
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
@endsection

@section('main-content')
<div class="pagetitle">
    <div class="d-flex justify-content-between">
        <div class="breadcrumb">
            <h1>{{ __('Homestay Report By Okupansi') }}</h1>
        </div>
        {{-- start daterangepicker --}}
        <form action="{{ route('reports.okupansi.homestays.index') }}" method="get" id="filterDate" class="col-4">
            <div class="form-row align-items-center">
                <div class="col-auto">
                    <span for="daterange">Filter Date: </span>
                </div>
                <div class="col">
                    <input class="form-control" type="text" id="daterange" name="daterange" value="{{ $defaultPeriod }}" />
                </div>
                @if (request()->except('page'))
                    <div class="col-auto">
                        <a href="{{ route('reports.okupansi.homestays.index') }}" class="btn btn-danger">Reset</a>
                    </div>
                @endif
            </div>
        </form>
        {{-- end daterangepicker --}}
    </div>
</div>

<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Stacked Bar Chart</h5>

                <!-- Stacked Bar Chart -->
                <canvas id="stakedBarChart" style="max-height: 400px;"></canvas>
                <script>
                    document.addEventListener("DOMContentLoaded", () => {
                    new Chart(document.querySelector('#stakedBarChart'), {
                        type: 'bar',
                        data: {
                        labels: @json($labels),
                        datasets: [
                            {
                                label: 'Persentase',
                                data: @json($data['total_length_of_stay']),
                                backgroundColor: [
                                    '#C1232B','#B5C334','#FCCE10','#E87C25'
                                ],
                                stack: 'Stack 0',
                            },
                        ]
                        },
                        options: {
                        plugins: {
                            title: {
                            display: true,
                            text: 'Period Homestay By Okupansi'
                            },
                        },
                        responsive: true,
                        scales: {
                            x: {
                            stacked: true,
                            },
                            y: {
                            stacked: true
                            },
                        },
                        },
                    });
                    });
                </script>
                <!-- End Stacked Bar Chart -->
              </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <a href="{{ route('reports.okupansi.export', request()->query()) }}" class="btn btn-warning">Export</a>
        </div>
        <br>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
            <div class="card-body">
                <br>
                <!-- Table with stripped rows -->

                <table class="table datatable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th scope="col">Homestay</th>
                        <th scope="col">Total Malam</th>
                        <th scope="col">Persentase Period</th>
                    </tr>
                </thead>
                    <tbody>
                        @php
                            $no = 1;
                        @endphp
                        @forelse ($reservations as $reservation)
                        <tr>
                            <td class="align-middle">{{ $no++ }}</td>
                            <td>{{ $reservation->homestay_name }}</td>
                            <td>{{ $reservation->total_length_of_stay }}</td>
                            <td>{{ number_format(($reservation->total_length_of_stay / $period) * 100) }} %</td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="4" text-align="center">Tidak Ada Data</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
                <!-- End Table with stripped rows -->
                {{-- <hr> --}}

                {{-- <x-pagination :paginated="$reservations"></x-pagination> --}}

            </div>
            </div>

        </div>
    </div>
</section>
@endsection

@section('page-js')
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

    <script>
        $(function() {
            $('#daterange').daterangepicker({
                opens: 'left',
                autoUpdateInput: false,
                locale: {
                    cancelLabel: 'Clear'
                }
            }).on('apply.daterangepicker', function(ev, picker) {
                $(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY'));
                $('#filterDate').submit();
            });
        });
    </script>

    <script>
        $(document).ready(function() {


        })
    </script>
@endsection