routes/web.php
<?php

use App\Http\Controllers\Dashboard\ChannelController;
use App\Http\Controllers\Dashboard\CustomerController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\HomestayController;
use App\Http\Controllers\Dashboard\Report\Okupansi\HomestayReportByOkupansiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\AsalCustomerByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\ChannelByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\DaerahHHomestayByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\HomestayByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\JumlahOrangByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\RoomHomestayByTransaksiController;
use App\Http\Controllers\Dashboard\ReservationController;
use App\Http\Controllers\Dashboard\ServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Route::prefix('/d')->group(function () {
    Route::resource('dashboard', DashboardController::class)->only('index');

    Route::resource('customer', CustomerController::class)->only('index');

    Route::resource('services', ServiceController::class)->only('index');

    Route::resource('channels', ChannelController::class)->only('index');

    Route::resource('homestays', HomestayController::class)->only('index');

    Route::resource('reservations', ReservationController::class)->only('index');

    Route::prefix('reports')->name('reports.')->group(function() {

        Route::prefix('transaksi')->name('transaksi.')->group(function() {
            Route::get('export-homestay', [HomestayByTransaksiController::class, 'export'])->name('export-homestay');
            Route::get('export-channel', [ChannelByTransaksiController::class, 'export'])->name('export-channel');
            Route::get('export-jumlah-orang', [JumlahOrangByTransaksiController::class, 'export'])->name('export-jumlah-orang');
            Route::get('export-daerah-homestay', [DaerahHHomestayByTransaksiController::class, 'export'])->name('export-daerah-homestay');
            Route::get('export-asal-customer', [AsalCustomerByTransaksiController::class, 'export'])->name('export-asal-customer');
            Route::get('export-room-homestay', [RoomHomestayByTransaksiController::class, 'export'])->name('export-room-homestay');

            Route::resource('homestays', HomestayByTransaksiController::class)->only('index');
            Route::resource('channel', ChannelByTransaksiController::class)->only('index');
            Route::resource('jumlah-orang', JumlahOrangByTransaksiController::class)->only('index');
            Route::resource('daerah-homestay', DaerahHHomestayByTransaksiController::class)->only('index');
            Route::resource('asal-customer', AsalCustomerByTransaksiController::class)->only('index');
            Route::resource('room-homestay', RoomHomestayByTransaksiController::class)->only('index');
        });

        Route::prefix('okupansi')->name('okupansi.')->group(function() {
            Route::get('export', [HomestayReportByOkupansiController::class, 'export'])->name('export');
            Route::resource('homestays', HomestayReportByOkupansiController::class)->only('index');
        });
    });

});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    public function province()
    {
        return $this->belongsTo(Province::class);
    }
}

app/Http/Controllers/Dashboard/CustomerController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    public function index(Request $request)
    {
        $customers = Customer::paginate();

        if ($request->has('search')) {
            $search = $request->query('search');
            $customers->where(function ($query) use ($search) {
                $query->where('name', 'LIKE', '%' . $search . '%');
            });
        }

        return view('pages.customers.index', compact('customers'));
    }
}

resources/views/pages/customers/index.blade.php
@extends('layouts.master')
@section('title', 'Orders')

@section('main-content')
<div class="pagetitle">
    <h1>Customer</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item">Customer</li>
      </ol>
    </nav>
</div>

<section class="section">
    <div class="row">
      <div class="col-lg-12">

        <div class="card">
          <div class="card-body">
            <br>
            <div class="row mb-3">
                <div class="col-12" id="general">
                    <form action="{{ route('customer.index') }}" method="get" id="formSearch">
                        <div class="row">
                            <div class="col mb-3 mb-md-0">
                                <input type="text" name="search" class="form-control" placeholder="Cari Customer" value="{{ request()->query('search') }}">
                            </div>
                            @if (request()->except('page'))
                                <div class="col-auto">
                                    <a href="{{ route('customer.index') }}" class="btn btn-danger">Reset</a>
                                </div>
                            @endif
                        </div>
                    </form>
                </div>
            </div>
            <!-- Table with stripped rows -->
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Province</th>
                  <th scope="col">Email</th>
                  <th scope="col">Phone</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($customers as $customer)
                    <tr>
                        <td class="align-middle">{{ ($customers->currentPage() - 1) * $customers->perPage() + $loop->iteration }}</td>
                        <td>{{ $customer->name }}</td>
                        <td>{{ $customer->province->name }}</td>
                        <td>{{ $customer->email }}</td>
                        <td>{{ $customer->phone }}</td>
                    </tr>
                @endforeach
              </tbody>
            </table>
            <!-- End Table with stripped rows -->

            <hr>

            <x-pagination :paginated="$customers"></x-pagination>


          </div>
        </div>

      </div>
    </div>
  </section>
@endsection