routes/web.php
<?php

use App\Http\Controllers\Dashboard\ChannelController;
use App\Http\Controllers\Dashboard\CustomerController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\HomestayController;
use App\Http\Controllers\Dashboard\Report\Okupansi\HomestayReportByOkupansiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\AsalCustomerByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\ChannelByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\DaerahHHomestayByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\HomestayByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\JumlahOrangByTransaksiController;
use App\Http\Controllers\Dashboard\Report\Transaksi\RoomHomestayByTransaksiController;
use App\Http\Controllers\Dashboard\ReservationController;
use App\Http\Controllers\Dashboard\ServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Route::prefix('/d')->group(function () {
    Route::resource('dashboard', DashboardController::class)->only('index');

    Route::resource('customer', CustomerController::class)->only('index');

    Route::resource('services', ServiceController::class)->only('index');

    Route::resource('channels', ChannelController::class)->only('index');

    Route::resource('homestays', HomestayController::class)->only('index');

    Route::resource('reservations', ReservationController::class)->only('index');

    Route::prefix('reports')->name('reports.')->group(function() {

        Route::prefix('transaksi')->name('transaksi.')->group(function() {
            Route::get('export-homestay', [HomestayByTransaksiController::class, 'export'])->name('export-homestay');
            Route::get('export-channel', [ChannelByTransaksiController::class, 'export'])->name('export-channel');
            Route::get('export-jumlah-orang', [JumlahOrangByTransaksiController::class, 'export'])->name('export-jumlah-orang');
            Route::get('export-daerah-homestay', [DaerahHHomestayByTransaksiController::class, 'export'])->name('export-daerah-homestay');
            Route::get('export-asal-customer', [AsalCustomerByTransaksiController::class, 'export'])->name('export-asal-customer');
            Route::get('export-room-homestay', [RoomHomestayByTransaksiController::class, 'export'])->name('export-room-homestay');

            Route::resource('homestays', HomestayByTransaksiController::class)->only('index');
            Route::resource('channel', ChannelByTransaksiController::class)->only('index');
            Route::resource('jumlah-orang', JumlahOrangByTransaksiController::class)->only('index');
            Route::resource('daerah-homestay', DaerahHHomestayByTransaksiController::class)->only('index');
            Route::resource('asal-customer', AsalCustomerByTransaksiController::class)->only('index');
            Route::resource('room-homestay', RoomHomestayByTransaksiController::class)->only('index');
        });

        Route::prefix('okupansi')->name('okupansi.')->group(function() {
            Route::get('export', [HomestayReportByOkupansiController::class, 'export'])->name('export');
            Route::resource('homestays', HomestayReportByOkupansiController::class)->only('index');
        });
    });

});

resources/views/layouts/footer.blade.php
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
</footer>

resources/views/layouts/header.blade.php
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

<div class="d-flex align-items-center justify-content-between">
    <a href="index.html" class="logo d-flex align-items-center">
    <img src="assets/img/logo.png" alt="">
    <span class="d-none d-lg-block">Whouse Dashboard</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
</div><!-- End Logo -->




</header><!-- End Header -->

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>@yield('title') | {{ config('app.name') }}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ asset('assets') }}/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="{{ asset('assets') }}/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="{{ asset('assets') }}/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="{{ asset('assets') }}/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="{{ asset('assets') }}/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="{{ asset('assets') }}/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="{{ asset('assets') }}/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ asset('assets') }}/css/style.css" rel="stylesheet">
  @yield('page-css')

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.2.2
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    @include('layouts.header')

    @include('layouts.sidebar')

    <main id="main" class="main">

    @yield('main-content')

    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    {{-- @include('layouts.footer') --}}
    <!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{{ asset('assets') }}/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="{{ asset('assets') }}/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('assets') }}/vendor/chart.js/chart.min.js"></script>
  <script src="{{ asset('assets') }}/vendor/echarts/echarts.min.js"></script>
  <script src="{{ asset('assets') }}/vendor/quill/quill.min.js"></script>
  <script src="{{ asset('assets') }}/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="{{ asset('assets') }}/vendor/tinymce/tinymce.min.js"></script>
  <script src="{{ asset('assets') }}/vendor/php-email-form/validate.js"></script>
  @yield('page-js')

  <!-- Template Main JS File -->
  <script src="{{ asset('assets') }}/js/main.js"></script>


</body>

</html>

resources/views/layouts/sidebar.blade.php
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link " href="{{ route('dashboard.index') }}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-heading">Report</li>

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#report-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-layout-text-window-reverse"></i><span>Report Occupant</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="report-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ route('reports.okupansi.homestays.index') }}">
                    <i class="bi bi-circle"></i><span>Homestays</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Charts Nav -->
        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#report-transaction-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-layout-text-window-reverse"></i><span>Report Transactions</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="report-transaction-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ route('reports.transaksi.homestays.index') }}">
                    <i class="bi bi-circle"></i><span>Homestay</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('reports.transaksi.channel.index') }}">
                    <i class="bi bi-circle"></i><span>Channel Pemesanan</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('reports.transaksi.jumlah-orang.index') }}">
                    <i class="bi bi-circle"></i><span>Jumlah Orang</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('reports.transaksi.daerah-homestay.index') }}">
                    <i class="bi bi-circle"></i><span>Daerah Homestay</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('reports.transaksi.asal-customer.index') }}">
                    <i class="bi bi-circle"></i><span>Asal Customer</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('reports.transaksi.room-homestay.index') }}">
                    <i class="bi bi-circle"></i><span>Room Homestay</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Charts Nav -->


        <li class="nav-heading">Customer</li>

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#customers-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-layout-text-window-reverse"></i><span>Customer</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="customers-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ route('customer.index') }}">
                    <i class="bi bi-circle"></i><span>All Customer</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Charts Nav -->

        <li class="nav-heading">Master Data</li>

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#homestay-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-layout-text-window-reverse"></i><span>Homestay</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="homestay-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ route('homestays.index') }}">
                    <i class="bi bi-circle"></i><span>All Homestay</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#channel-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-layout-text-window-reverse"></i><span>Channel</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="channel-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ route('channels.index') }}">
                    <i class="bi bi-circle"></i><span>All Channel</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#service-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-layout-text-window-reverse"></i><span>Service</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="service-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ route('services.index') }}">
                    <i class="bi bi-circle"></i><span>All Service</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="nav-heading">Reservation</li>

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#order-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-layout-text-window-reverse"></i><span>Reservations</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="order-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ route('reservations.index') }}">
                    <i class="bi bi-circle"></i><span>All Reservation</span>
                    </a>
                </li>
            </ul>
        </li>


    </ul>

</aside><!-- End Sidebar-->